### ISSUE TITLE
ZulfBungee error NoClassDefFoundError (ch/njol/skript/lang/Section)

### ISSUE THREAD

**Issue by Speccy42** [Zulfen/ZulfBungee#28]
**Describe the bug**
When launching the plugin, an error appears and deactivate the plugin.

**Spigot server information (in this order)**
 - Plugin version 0.9.7
 - Minecraft Version: Paper-1.12.2
 - Skript Version 2.5.3
 - Java Version 8

**Proxy information (in this order)**
 - Proxy Type Bungeecord
 - Minecraft Version: 1.16
 - Java Version 8

**Additional context**
Error occurred while enabling ZulfBungee v0.9.7 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/lang/Section
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Software.jar:git-Paper-18a678b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:348) ~[?:?]
	at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
	at tk.zulfengaming.zulfbungee.spigot.ZulfBungeeSpigot.onEnable(ZulfBungeeSpigot.java:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:396) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:345) ~[Software.jar:git-Paper-18a678b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:447) ~[Software.jar:git-Paper-18a678b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:408) ~[Software.jar:git-Paper-18a678b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:346) ~[Software.jar:git-Paper-18a678b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) ~[Software.jar:git-Paper-18a678b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:621) ~[Software.jar:git-Paper-18a678b]
	at java.lang.Thread.run(Thread.java:750) [?:?]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.lang.Section
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[Software.jar:git-Paper-18a678b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Software.jar:git-Paper-18a678b]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:?]
	... 24 more

**Comment by Speccy42** [comment]
I just saw that it's from the Script version. Version 2.6.4 works.
