### ISSUE TITLE
ZulfBungee Mysql bug

### ISSUE THREAD

**Issue by TUSZzzz** [Zulfen/ZulfBungee#50]
When I use MySQL as my storage solution, it doesn’t work properly regardless of any settings, including [mysql-use-ssl: false, mysql-verify-certificate: false]. However, this is just a minor issue. I just want to ask, is there a storage limit for this data? Because I plan to use it for a cross-server player inventory system

**Comment by Zulfen** [comment]
Do you get any errors? As for storage limit, there isn't one - as long as you have enough disk space!

**Comment by TUSZzzz** [comment]
Sorry i busy thess days

```
[07:15:14 INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[07:15:14 ERROR]: Exception in task com.zulfen.zulfbungee.universal.managers.MainServer$$Lambda/0x000002239a815360@57c5f218 by plugin zulfbungee
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/plugin?&useSSL=false
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:114) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:331) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:114) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:108) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
        at com.zulfen.zulfbungee.universal.storage.HikariSQLImpl.setupDatabase(HikariSQLImpl.java:36) ~[?:?]
        at com.zulfen.zulfbungee.universal.managers.MainServer.lambda$new$0(MainServer.java:61) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.4.0-SNAPSHOT (git-1db8c8c6-b
458)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300) ~[java.sql:?]
        at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:106) ~[?:?]
        ... 10 more
```

**Comment by Zulfen** [comment]
Try the latest artifact in the commit I pushed recently, I supply a MySQL driver with ZulfBungee now.

**Comment by TUSZzzz** [comment]
ok sir

**Comment by TUSZzzz** [comment]
[23:55:46 ERROR]: Exception in task com.zulfen.zulfbungee.universal.managers.MainServer$$Lambda/0x000002155f8dcea8@1d3bf525 by plugin zulfbungee
java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/plugin?&useSSL=false
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:115) ~[?:?]
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:330) ~[?:?]
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:116) ~[?:?]
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:94) ~[?:?]
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111) ~[?:?]
        at com.zulfen.zulfbungee.universal.storage.HikariSQLImpl.setupDatabase(HikariSQLImpl.java:36) ~[?:?]
        at com.zulfen.zulfbungee.universal.managers.MainServer.lambda$new$0(MainServer.java:61) ~[?:?]
        at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285) ~[velocity.jar:3.4.0-SNAPSHOT (git-876b9c36-b
465)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
Caused by: java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300) ~[java.sql:?]
        at com.zulfen.zulfbungee.libs.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:107) ~[?:?]
        ... 10 more

[23:58:00 ERROR] [zulfbungee]: Unhandled exception occurred in connection with address /127.0.0.1:30002
[23:58:00 ERROR]: java.lang.RuntimeException: Failed to get driver instance for jdbcUrl=jdbc:mysql://127.0.0.1:3306/plugin?&useSSL=false
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:115)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:330)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:116)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:94)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.storage.HikariSQLImpl.setVariable(HikariSQLImpl.java:143)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.handlers.proxy.packets.NetworkVariableModify.handlePacket(NetworkVariableModify.java:38)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.managers.PacketHandlerManager.handlePacket(PacketHandlerManager.java:49)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.socket.ProxyServerConnection.consume(ProxyServerConnection.java:108)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.handlers.CommunicationHandler.processLoop(CommunicationHandler.java:33)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.universal.socket.ProxyServerConnection.lambda$start$2(ProxyServerConnection.java:49)
[23:58:00 ERROR]:       at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$0(VelocityScheduler.java:285)
[23:58:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:58:00 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:58:00 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1575)
[23:58:00 ERROR]: Caused by: java.sql.SQLException: No suitable driver
[23:58:00 ERROR]:       at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:300)
[23:58:00 ERROR]:       at com.zulfen.zulfbungee.libs.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:107)
[23:58:00 ERROR]:       ... 14 more

**Comment by Zulfen** [comment]
Hi,
Tested it myself and the latest build does fix the issue. I have changed the syntax of some stuff slightly so let me know if your scripts break.
